apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-messages
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
    - name: echo-again
      image: ubuntu
      command:
        - echo
      args:
        - "Another echo message"
    - name: third-step
      image: ubuntu
      command:
        - echo
      args:
        - "Third echo message"
