apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-pi
spec:
  steps:
    - name: pi
      image: perl
      command:
        - perl
      args:
        - "-Mbignum=bpi"
        - "-wle"
        - "print bpi(2000)"
