apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-hello-world-task-run
spec:
  taskRef:
    name: echo-hello-world
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-pi-task-run
spec:
  taskRef:
    name: echo-pi
